Remove conditional https couchdb protocol
https://github.com/opscode-cookbooks/couchdb has no https attribute.
Including this conditional causes the following stack trace failure when
wrapping this cookbook:

    -*- mode: rspec-compilation; default-directory: "~/Development/***-npm-registry/" -*-
    RSpec Compilation started at Tue Dec  3 13:33:46

    bundle exec rspec --format documentation /home/jackcviers/Development/***-npm-registry/spec

    *** npm registry default

    ================================================================================
    Recipe Compile Error in /tmp/d20131203-29290-9i5hpz/***-npm-registry/recipes/default.rb
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /tmp/d20131203-29290-9i5hpz/npm_registry/recipes/default.rb:21:in `from_file'
    /tmp/d20131203-29290-9i5hpz/***-npm-registry/recipes/default.rb:1:in `from_file'

    Relevant File Content:
    ----------------------
    /tmp/d20131203-29290-9i5hpz/npm_registry/recipes/default.rb:

    14:  # distributed under the License is distributed on an "AS IS" BASIS,
    15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    16:  # See the License for the specific language governing permissions and
    17:  # limitations under the License.
    18:  #
    19:  #
    20:
    21>> node.default['npm_registry']['registry']['url'] = "#{!node['couch_db']['config']['couchdb']['httpsd'] ? 'http' : 'https'}://localhost:#{node['couch_db']['config']['httpd']['port']}"
    22:
    23:  _npm_registry = node['npm_registry'];
    24:  _git = _npm_registry['git']
    25:  _couch_db = node['couch_db']
    26:  _config = _couch_db['config']
    27:  _httpd = _config['httpd']
    28:  _couchdb = _config['couchdb']
    29:  _daemons = _config['daemons']
    30:  _registry = _npm_registry['registry']

    should include the upstream cookbook (FAILED - 1)

    Failures:

    1) *** npm registry default should include the upstream cookbook
    Failure/Error: ChefSpec::Runner.new do |node|
    NoMethodError:
    undefined method `[]' for nil:NilClass
    # /tmp/d20131203-29290-9i5hpz/npm_registry/recipes/default.rb:21:in `from_file'
    # /tmp/d20131203-29290-9i5hpz/***-npm-registry/recipes/default.rb:1:in `from_file'
    # ./spec/***_npm_registry_default_spec.rb:5:in `block (2 levels) in <top (required)>'
    # ./spec/***_npm_registry_default_spec.rb:11:in `block (2 levels) in <top (required)>'

    Finished in 0.29931 seconds
    1 example, 1 failure

    Failed examples:

    rspec ./spec/***_npm_registry_default_spec.rb:10 # *** npm registry default should include the upstream cookbook

Update to use couchdb default node attrs
Check replication flavor for scheduling
Add vendor cookbooks to gitignore